### ISSUE TITLE
您好，我在sh run.sh之后，代码报了错TypeError: __init__() takes 1 positional argument but 4 were given，请问这个问题是什么原因呀，感谢！

### ISSUE THREAD

**Issue by A465539338** [CPFLAME/centerX#17]
[12/22 10:43:48 d2.data.common]: Serializing 117266 elements to byte tensors and concatenating them all ...
[12/22 10:43:52 d2.data.common]: Serialized dataset takes 451.21 MiB
[12/22 10:43:52 detectron2]: Using training sampler TrainingSampler
[12/22 10:43:57 detectron2]: initial from https://download.pytorch.org/models/resnet18-5c106cde.pth
[12/22 10:43:57 detectron2]: The checkpoint state_dict contains keys that are not used by the model:
  fc.{weight, bias}
Traceback (most recent call last):
  File "/home/yb/centerX/train_net.py", line 66, in <module>
    args=(args,),
  File "/home/yb/anaconda3/envs/centernetx/lib/python3.7/site-packages/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/yb/anaconda3/envs/centernetx/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yb/anaconda3/envs/centernetx/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/yb/anaconda3/envs/centernetx/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/yb/anaconda3/envs/centernetx/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/yb/anaconda3/envs/centernetx/lib/python3.7/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/yb/centerX/train_net.py", line 52, in main
    trainer = Trainer(cfg)
  File "/home/yb/centerX/engine/defaults.py", line 71, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
TypeError: __init__() takes 1 positional argument but 4 were given

**Comment by CPFLAME** [comment]
可能是你的detectron2版本问题。建议按照readme中的指令安装detectron2
pip install -U 'git+https://github.com/CPFLAME/detectron2.git'

**Comment by yticad** [comment]
I met the same problem. I installed the latest detectron2 (python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html).

How can I modify your code to use the official detectron2 instead of your version? Thanks.

**Comment by A465539338** [comment]
感谢作者给出的建议，我重新配置了环境并成功运行了。环境如下：

python 3.7
pytorch 1.5
cuda 10.1
detectron2 用这个来安装pip install -U 'git+https://github.com/CPFLAME/detectron2.git'， 不能按照官方的命令来安装

**Comment by lixiangMindSpore** [comment]
> pip install -U 'git+[https://github.com/CPFLAME/detectron2.git'](https://github.com/CPFLAME/detectron2.git'%EF%BC%8C)

![image](https://user-images.githubusercontent.com/78945582/189845595-d4b6d762-11a5-4b88-abdc-d0015c15c1de.png)
按照指导安装不成功，请教一下，如何解决？
