### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 4 were given

### ISSUE THREAD

**Issue by zyrant** [CPFLAME/centerX#32]
Traceback (most recent call last):
  File "train_net.py", line 77, in <module>
    args=(args,),
  File "/home/zy/anaconda3/envs/CenterNet/lib/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "train_net.py", line 63, in main
    trainer = Trainer(cfg)
  File "/home/zy/Downloads/2222/engine/defaults.py", line 71, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
TypeError: __init__() takes 1 positional argument but 4 were given

您好, 请问这个问题怎么解决？

**Comment by CPFLAME** [comment]
应该是安装的detectron2版本不对，这个issue下面有相同的问题
https://github.com/JDAI-CV/centerX/issues/17#issue-772594795

**Comment by zyrant** [comment]
感谢回复，我试试。
