### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by kike-0304** [CPFLAME/centerX#48]
Traceback (most recent call last):
  File "train_net.py", line 66, in <module>
    args=(args,),
  File "/home/cc631/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 52, in main
    trainer = Trainer(cfg)
  File "/home/cc631/hailong/code/Dilated-FPN/centerX/engine/defaults.py", line 71, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
TypeError: __init__() takes 1 positional argument but 4 were given

**Comment by oliverwxg** [comment]
这个问题解决了吗？是版本不对吗？

**Comment by TonyzBi** [comment]
I Got the the error, When I switched detectron2 to  Version 0.2.1, It works.

**Comment by liujia761** [comment]
> 回溯（最近一次调用最后一次）： 文件“train_net.py”，第 66 行，在 args=(args,) 中， 文件“/home/cc631/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages /detectron2/engine/launch.py​​”，第 82 行，启动 main_func(*args) 文件“train_net.py”，第 52 行，主 训练器 = Trainer(cfg) 文件“/home/cc631/hailong/code/Dilated -FPN/centerX/engine/defaults.py”，第 71 行，在**init** super(DefaultTrainer, self) 中。**init** (model, data_loader, optimizationr) TypeError: **init** () 需要 1 个位置参数，但给出了 4 个

您好，请问我如何使用此代码来训练自己得模型
